### ISSUE TITLE
들여쓰기

### ISSUE THREAD

**Issue by ajb3296** [ABER1047/University-programming-class-Practicing#1]
들여쓰기 똑바로 하세요. 진짜 중요합니다.

함수 뒤 중괄호 쓰기 전 개행 안하는게 더 깔끔합니다. 이건 개인취향 문제라 맘대로 해도 될듯.

사칙연산 기호 양 옆은 띄우는게 보기 좋아요, 다만 변수를 음수로 만들기 위한 - 기호는 예외.
ex) System.out.println(name + ", " + age + ", " + tall + ", " + weight + " / ");

for 문 혹은 if 문 뒤에 열리는 소괄호는 띄워주고 쓰는게 좋습니다.
ex) if (뭐시기뭐시기) 혹은 for (뭐시기뭐시기)

나머지는 깔끔한듯.

**Comment by ABER1047** [comment]
허걱;; 이 누추한곳에 귀한분이;;

띄어쓰기 같은거는 기존에 쓰던 프로그래밍 언어 습관이라던가 여러가지 이유들 때문에 고치기 힘들더라구요;;
특히나 지적해주신 함수 뒤 중괄호나 프린트때 사용한 +기호 같은거는 제가 보기 힘들어서 일부러 저렇게 쓴것도 있습니다

보통은
 if (){
}
로 많이 쓰시던데 저는 이거 너무 보기 불편해서 기존 존재 하는 코드도 싹다 고쳐서
if ()
{
}
로 만들고 보거든요;;

프린트때 사용한 + 같은 경우도 ", " 때문에 ""안에 띄어쓰기가 있는건지, 
+ 앞뒤에 띄어쓰기가 있는건지 한번에 눈에 안들어와서 구분할려고 그렇게 썼습니다
(보통 이런경우는, ""+(변수)+""+(변수) 식으로 사용하긴 합니다)


근데 들여쓰기 부분은 어느 부분을 보시고 이야기 하신건지 잘 모르겠네요;;
